[package]
name = "ast-net"
description = "Antimicrobial Susceptibility Testing Network (AST-Net)"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"
license = "Unlicense"
readme = "README.md"

[lib]
name = "ast_net"
crate-type = ["cdylib"]

[dependencies]
imgal = "0.3"
ndarray = "0.17"
tiff = "0.11"
