[build-system]
requires = ["maturin>=1.8.3"]
build-backend = "maturin"

[project]
name = "ast-net"
version = "0.1.0.dev0"
description = "AST-net."
authors = [{ name = "Edward Evans" }]
license = {text = "MIT OR Unlicense"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
]
keywords = ["image-processing", "algorithm"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering",
]
